module.exports = {
    LANGUAGE_TYPE:{
        DEFAULT:'en',
        ENGLISH:'en',
        ARABIC:'ar'
    },
    EVENT_TYPE:{
        DEFAULT:'DEFAULT'
    },
    SOCKET_TYPE:{
        BROAD_CAST:'BROAD_CAST',
        USER:'USER',
        ADMIN:'ADMIN'
    },
    PAYMENT_MODE:{
        CASH:'CASH',
        CARD:'CARD',
        WALLET:'WALLET'
    },
    PAYMENT_STATUS:{
        PENDING:'PENDING',
        COMPLETED:'COMPLETED'
    },
    BOOKING_STATUS:{
        PENDING:'PENDING',
        ACCEPTED:'ACCEPTED',
        COMPLETED:'COMPLETED',
        ARRIVED:'ARRIVED',
        STARTED:'STARTED',
        ONGOING:'ONGOING',
        CANCELED:'CANCELED'
    },
    FILE_PATH:{
        ADMIN:'/static/admin',
        USER:'/static/user'
    },
    SMS_EVENT_TYPE:{
        SEND_OTP:'SEND_OTP'
    },
    DEFAULT_LIMIT:10,
    DEFAULT_SKIP:0,
    DEFAULT_RISK_AMOUNT:20,
    RUNDOWN_API_TOKEN:'f7f1a28778msh022a2a8c3aa3518p155dcbjsnfa05f4a23bfa',
    RUNDOWN_API_URL:'https://therundown-therundown-v1.p.rapidapi.com',
    RUNDOWN_API_NAME:{
        SPORTS:1,
        EVENT:2,
        SPORTS_BY_DATE:3
    },
    RUNDOWN_API_TIME_PARAM:{
        HOURS:'hours',
        MINUTES:'minutes',
        DAYS:'days',
        SECOND:'second'
    },
    RUNDOWN_API_TIME:{
        TIME_SPORT_LIST_API:24,
        TIME_EVENT_API:12,
        LIVE_PAST_TIME_EVENT_API:1,
        LIVE_FUTURE_TIME_EVENT_API:1,
        TIME_SPORTS_BY_DATE_API:2,
        CRON_CHECK_TIME:23
    },
    SPORTS_LIST:{
        NCAAF:1,
        NFL:2,
        MLB:3,
        NBA:4,
        NCAAM:5,
        NHL:6,
        MLS:10
    },
    AFFILIATED_LIST:{
      DIMES_5:1,
      BOVADA:2,
      PINNACLE:3,
      BET_ONLINE:6,
      BOOKMARKER:7
    },
    LAST_BETS:{
        LAST_10_BETS:10,
        LAST_50_BETS:50,
        LAST_100_BETS:100,
        ALL_BETS:0
    }
};
